<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inria+Serif:wght@400&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@400&display=swap" />
    <link rel="stylesheet" href="index.css" />
  </head>
  <body>
    <div
      style="width:2458px;height:1185px;background-color:#f1ebe5;position:relative;overflow:hidden;margin:0 auto"
      class="main-container"
    >
    <div
      style="width:118px;height:89px;background-position:center;background-image:url(/fyp/photo/logo.png);background-size:cover;background-repeat:no-repeat;position:relative;z-index:12;margin:0 0 0 3px"
    ></div>
    <div
      style="width: 1000px;px;height:1024px;background-position:center;background-image:url(/fyp/photo/handshake.jpg);background-size:cover;background-repeat:no-repeat;position:absolute;top:81px;left:1115px;z-index:10"
    >
      <span
        style="display:flex;height:37px;justify-content:flex-start;align-items:flex-start;font-family:Inknut Antiqua, var(--default-font-family);font-size:32px;font-weight:400;line-height:37px;color:#000000;position:absolute;bottom:149px;left:calc(50% - 238.5px);text-align:left;white-space:nowrap;z-index:10"
        >Events Tailored to Perfection</span
      >
    </div>
      <div
        style="width:446px;height:653px;position:absolute;top:264px;left:238px;z-index:6"
      >
        <button
          style="width:446px;height:91px;border:1px solid #000000;position:relative;overflow:hidden;cursor:pointer;margin:0 0 0 0;background:transparent"
        >
          <span
            style="display:flex;height:42px;justify-content:flex-start;align-items:flex-start;font-family:Inria Serif, var(--default-font-family);font-size:32px;font-weight:400;line-height:41.6px;color:#000000;position:absolute;top:calc(50% - 21.5px);left:calc(50% - 53px);text-align:left;white-space:nowrap;z-index:1"
            >Menu</span
          ></button
        ><button
          style="width:446px;height:91px;border:1px solid #000000;position:relative;overflow:hidden;z-index:6;cursor:pointer;margin:111px 0 0 0;background:transparent"
        >
          <span
            style="display:flex;height:42px;justify-content:flex-start;align-items:flex-start;font-family:Inria Serif, var(--default-font-family);font-size:32px;font-weight:400;line-height:41.6px;color:#000000;position:absolute;top:calc(50% - 21.5px);left:calc(50% - 139px);text-align:left;white-space:nowrap;z-index:7"
            >Upcoming Event</span
          ></button
        ><a
          style="display:block;width:446px;height:91px;border:1px solid #000000;position:relative;overflow:hidden;z-index:4;cursor:pointer;margin:89px 0 0 0;background:transparent;text-decoration:none"
          href="/fyp/register/book_event.php"
        >
          <span
            style="display:flex;height:42px;justify-content:flex-start;align-items:flex-start;font-family:Inria Serif, var(--default-font-family);font-size:32px;font-weight:400;line-height:41.6px;color:#000000;position:absolute;top:calc(50% - 21.5px);left:calc(50% - 103px);text-align:left;white-space:nowrap;z-index:5"
            >Create Event</span
          ></a
        ><button
          style="width:446px;height:91px;border:1px solid #000000;position:relative;overflow:hidden;z-index:2;cursor:pointer;margin:89px 0 0 0;background:transparent"
        >
          <span
            style="display:flex;height:42px;justify-content:flex-start;align-items:flex-start;font-family:Inria Serif, var(--default-font-family);font-size:32px;font-weight:400;line-height:41.6px;color:#000000;position:absolute;top:calc(50% - 21.5px);left:calc(50% - 103px);text-align:left;white-space:nowrap;z-index:3"
            >View Booking
          </span>
        </button>
      </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
