<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@600;700&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" />
    <link rel="stylesheet" href="index.css" />
  </head>
  <body>
    <div
      style="width:1400px;height:800px;position:relative;margin:0 auto"
      class="main-container"
    >
      <div
        style="width:1400px;height:800px;background-color:#fffbf8;position:absolute;top:0;left:0;overflow:hidden"
      >
        <div
          style="width:1374.827px;height:785.078px;position:relative;overflow:visible auto;z-index:1;margin:56px 0 0 25px"
        >
          <div
            style="width:793.51px;height:46px;position:relative;z-index:24;margin:0 0 0 456.963px"
          >
            <button
              style="width:110px;height:46px;background-color:#ef8d21;border-radius:100px;border:none;position:absolute;top:0;left:673.037px;z-index:9;cursor:pointer"
            ></button
            ><span
              style="display:flex;height:22px;justify-content:flex-start;align-items:flex-start;font-family:Nunito, var(--default-font-family);font-size:16px;font-weight:600;line-height:21.824px;color:#000000;position:absolute;top:12px;left:0;text-align:left;white-space:nowrap;z-index:7"
              >Home Services Contact Us</span
            ><a href="login.php" style="display:flex;height:22px;justify-content:flex-start;align-items:flex-start;font-family:Nunito, var(--default-font-family);font-size:16px;font-weight:700;line-height:21.824px;color:#000000;position:absolute;top:12px;left:602.079px;text-align:left;white-space:nowrap;z-index:8;text-decoration:none"
              >Login</a
            ><a href="signup.php" style="display:flex;height:22px;justify-content:flex-start;align-items:flex-start;font-family:Nunito, var(--default-font-family);font-size:16px;font-weight:700;line-height:21.824px;color:#ffffff;position:absolute;top:12px;left:690.59px;text-align:left;white-space:nowrap;z-index:10;text-decoration:none"
              >Sign UP</a
            >
            <div
              style="width:33.449px;height:2px;background-position:center;background-image:url(./assets/images/3c7bf25f-bf00-4aee-9c4e-d2143f3f738d.png);background-size:cover;background-repeat:no-repeat;position:absolute;top:34px;left:2.573px;z-index:24"
            ></div>
          </div>
          <div
            style="width:107.036px;height:104px;background-position:center;background-image:url(./assets/images/2814000c-b0c7-4e36-9915-40cf482eeb82.png);background-size:cover;background-repeat:no-repeat;position:relative;z-index:14;margin:23px 0 0 956.123px"
          ></div>
          <div
            style="width:1374.827px;height:620.078px;position:relative;z-index:15;margin:-8px 0 0 0"
          >
            <div
              style="width:242.89px;height:236px;background-position:center;background-image:url(./assets/images/5b838c0d-e925-4341-a306-148a461bf6f4.png);background-size:cover;background-repeat:no-repeat;position:absolute;top:0;left:0;z-index:6"
            ></div>
            <div
              style="width:597.606px;height:580.155px;background-position:center;background-image:url(./assets/images/bc901bb6-41f3-4d98-b0fa-c7f8e764e306.png);background-size:cover;background-repeat:no-repeat;position:absolute;top:39.922px;left:777.221px;z-index:5"
            ></div>
            <span
              style="display:flex;height:74px;justify-content:flex-start;align-items:flex-start;font-family:Poppins, var(--default-font-family);font-size:49px;font-weight:400;line-height:73.5px;color:#364547;position:absolute;top:44px;left:65.868px;text-align:left;white-space:nowrap;z-index:11"
              >Fuzzy Event
            </span>
            <div
              style="width:569.495px;height:553.257px;background-position:center;background-image:url(./assets/images/73efa6fb-8ec7-423d-be07-5cd0d185db83.png);background-size:cover;background-repeat:no-repeat;position:absolute;top:53.372px;left:791.276px;z-index:4"
            ></div>
            <div
              style="width:528.333px;height:513.269px;background-position:center;background-image:url(./assets/images/54142058-1543-407c-8521-d0559d7637fe.png);background-size:cover;background-repeat:no-repeat;position:absolute;top:73.366px;left:811.857px;z-index:2"
            ></div>
            <div
              style="width:528.333px;height:513.269px;background-position:center;background-image:url(./assets/images/c3f4f432-7272-4af9-9339-f44a45ff94f3.png);background-size:cover;background-repeat:no-repeat;position:absolute;top:87px;left:816.152px;z-index:3"
            ></div>
            <span
              style="display:flex;height:105px;justify-content:flex-start;align-items:flex-start;font-family:Poppins, var(--default-font-family);font-size:70px;font-weight:700;line-height:105px;color:#364547;position:absolute;top:98px;left:59.693px;text-align:left;white-space:nowrap;z-index:12"
              >Build Your Dream Event</span
            ><span
              style="display:flex;width:567.087px;height:79px;justify-content:flex-start;align-items:flex-start;font-family:Poppins, var(--default-font-family);font-size:14px;font-weight:400;line-height:25px;color:#364547;letter-spacing:0.42px;position:absolute;top:219px;left:65.868px;text-align:left;z-index:13"
              >"Streamline your events effortlessly with our smart management
              system—plan, track, and succeed!"</span
            >
            <div
              style="width:624.722px;height:75px;position:absolute;top:323px;left:103.949px;z-index:15"
            >
              <div
                style="width:624.722px;height:75px;background-color:#ffffff;border-radius:50px;border:1px solid #ececec;position:absolute;top:0;left:0;box-shadow:0 4px 4px 0 rgba(0, 0, 0, 0.25);z-index:16"
              ></div>
              <button
                style="width:137.912px;height:46px;background-color:#ffffff;border-radius:100px;border:2px solid #000000;position:absolute;top:15px;left:453.875px;box-shadow:0 5px 2px 0 #ef8d21;z-index:19;cursor:pointer"
              ></button>
              <div
                style="width:1px;height:33.5px;background-position:center;background-image:url(./assets/images/bcad13ea-228a-4e4d-96d5-21c08e4ae425.png);background-size:cover;background-repeat:no-repeat;position:absolute;top:21px;left:144.617px;z-index:21"
              ></div>
              <div
                style="width:1px;height:33.5px;background-position:center;background-image:url(./assets/images/ebf7b769-a66d-4fdd-b930-a31fb419f691.png);background-size:cover;background-repeat:no-repeat;position:absolute;top:21px;left:304.142px;z-index:23"
              ></div>
              <span
                style="display:flex;height:23px;justify-content:flex-start;align-items:flex-start;font-family:Poppins, var(--default-font-family);font-size:15px;font-weight:400;line-height:22.5px;color:#8f8e8e;position:absolute;top:26px;left:45.285px;text-align:left;white-space:nowrap;z-index:17"
                >Plan </span
              ><span
                style="display:flex;height:23px;justify-content:flex-start;align-items:flex-start;font-family:Poppins, var(--default-font-family);font-size:15px;font-weight:400;line-height:22.5px;color:#8f8e8e;position:absolute;top:26px;left:179.08px;text-align:left;white-space:nowrap;z-index:18"
                >Organize</span
              ><span
                style="display:flex;height:23px;justify-content:flex-start;align-items:flex-start;font-family:Poppins, var(--default-font-family);font-size:15px;font-weight:400;line-height:22.5px;color:#8f8e8e;position:absolute;top:26px;left:338.605px;text-align:left;white-space:nowrap;z-index:22"
                >Execute</span
              ><span
                style="display:flex;height:22px;justify-content:flex-start;align-items:flex-start;font-family:Nunito, var(--default-font-family);font-size:16px;font-weight:700;line-height:21.824px;color:#000000;position:absolute;top:27px;left:471.371px;text-align:left;white-space:nowrap;z-index:20"
                >Book Now!!</span
              >
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
